export const COPY = {
  DISABLED: 'This command is not enabled in the server.',
  EMOJIS: {
    BALLOONS: '<:capybaraballoons:1363295432884617246>',
  },
  FEATURES: {
    BIRTHDAY: {
      NAME: 'birthday',
      DESCRIPTION: 'Add your birthday for a special greeting!',
      OPTION_MONTH_NAME: 'month',
      OPTION_MONTH_DESCRIPTION: 'Enter your birth month.',
      OPTION_DATE_NAME: 'date',
      OPTION_DATE_DESCRIPTION: 'Enter your birth date.',
      OPTION_TIMEZONE_NAME: 'timezone',
      OPTION_TIMEZONE_DESCRIPTION: 'Enter your timezone.',
    },
    COINFLIP: {
      NAME: 'coinflip',
      DESCRIPTION: 'Flip a coin!',
    },
    EIGHTBALL: {
      NAME: '8ball',
      DESCRIPTION: 'Play a game of Magic 8-Ball',
      OPTION_NAME: 'question',
      OPTION_DESCRIPTION: 'Enter your question.',
      RESPONSES: [
        'It is certain.',
        'It is decidedly so.',
        'Without a doubt.',
        'Yes - definitely.',
        'You may rely on it.',
        'As I see it, yes.',
        'Most likely.',
        'For sure.',
        'Yes.',
        'Signs point to yes.',
        'Reply hazy, try again.',
        'Ask again later.',
        'Better not tell you now.',
        'Cannot predict now.',
        'Concentrate and ask again.',
        "Don't count on it.",
        'My reply is no.',
        'No.',
        'Outlook not so good',
        'Very doubtful.',
      ],
    },
  },
  TIMEZONES: [
    'Pacific/Honolulu',
    'America/Anchorage',
    'America/Los_Angeles',
    'America/Phoenix',
    'America/Chicago',
    'America/New_York',
    'America/Santiago',
    'America/Sao_Paulo',
    'America/Noronha',
    'Atlantic/Cape_Verde',
    'Europe/London',
    'Europe/Berlin',
    'Africa/Cairo',
    'Europe/Moscow',
    'Asia/Dubai',
    'Asia/Karachi',
    'Asia/Kolkata',
    'Asia/Dhaka',
    'Asia/Yangon',
    'Asia/Ho_Chi_Minh',
    'Asia/Shanghai',
    'Asia/Seoul',
    'Australia/Melbourne',
    'Asia/Magadan',
    'Pacific/Auckland',
  ],
  TIMEZONE_ABBREVIATIONS: {
    'America/Santiago': 'CLT',
    'America/Sao_Paulo': 'BRT',
    'America/Noronha': 'FNT',
    'Atlantic/Cape_Verde': 'CVT',
    'Asia/Dubai': 'GST',
    'Asia/Dhaka': 'BST',
    'Asia/Yangon': 'MMT',
    'Asia/Ho_Chi_Minh': 'ICT',
    'Asia/Magadan': 'MAGT',
  },
};
